Перевод referece/react/components
reactjs/ru.react.dev pull request #841
Opened 2023-04-21 16:59 UTC by fpetrakov

2023-04-26 01:13 UTC, gcor reviewed
Спасибо!

2023-04-26 01:13 UTC, gcor commented on src/content/reference/react/components.md
> +Реакт из коробки предоставляет несколько компонентов.
```suggestion
React из коробки предоставляет несколько компонентов, которые можно использовать в JSX
```

2023-04-26 01:13 UTC, gcor commented on src/content/reference/react/components.md
> +title: "Встроенные реакт-компоненты"
```suggestion
title: "Встроенные react-компоненты"
```

2023-04-26 01:13 UTC, gcor commented on src/content/reference/react/components.md
> +Вы также можете [создавать свои компоненты](/learn/your-first-component), используя JavaScript функции.
```suggestion
Вы также можете [создавать свои компоненты](/learn/your-first-component), используя JavaScript-функции.
```

2023-04-26 16:57 UTC, fpetrakov commented on src/content/reference/react/components.md
> +Реакт из коробки предоставляет несколько компонентов.
Кажется, что "которые можно использовать в JSX" можно опустить, потому что все компоненты можно использовать в JSX

2023-05-02 11:53 UTC, ntishkevich requested changes

2023-05-02 11:53 UTC, ntishkevich commented on src/content/reference/react/components.md
> +title: "Встроенные react-компоненты"
```suggestion
title: "Встроенные React-компоненты"
```

2023-05-02 11:53 UTC, ntishkevich commented on src/content/reference/react/components.md
> +Реакт из коробки предоставляет несколько компонентов.
React превратился в Реакт, замечание от @gcor не до конца исправлено.

2023-05-02 11:53 UTC, ntishkevich commented on src/content/reference/react/components.md
> +* [`<Profiler>`](/reference/react/Profiler) измеряет производительность рендера компонентов.
```suggestion
* [`<Profiler>`](/reference/react/Profiler) позволяет вам измерять производительность рендеринга React-дерева программно.
```

2023-05-02 11:53 UTC, ntishkevich commented on src/sidebarReference.json
В ишью со списком страниц для перевода указано то, что `sidebarReference.json` и другие UI-ные штуки перевродить в самом конце, когда основная часть будет переведена. Просьба, далее не переводить.

2023-05-02 11:53 UTC, ntishkevich commented
Спасибо за перевод, небольшие комментарии.

2023-05-03 06:49 UTC, ntishkevich approved these changes
lgtm

2023-05-18 19:58 UTC, merged