Installation translation
reactjs/ru.react.dev pull request #842
Opened 2023-04-24 18:28 UTC by Palidos

Translation of Installation page

2023-04-26 00:08 UTC, gcor reviewed
Спасибо!

2023-04-26 00:08 UTC, gcor commented on src/content/learn/installation.md
> +React изначально был спроектирован так, чтобы его можно было внедрять постепенно. Другими словами, вы можете начать с малого и использовать только ту функциональность React, которая необходима вам в
```suggestion
React был спроектирован так, чтобы его можно было внедрять постепенно. Вы можете начать с малого и использовать только ту функциональность React, которая необходима вам в данный момент. Информация в этом разделе будет полезна как при первом знакомстве с React, так и при создании простой динамической HTML-страницы или проектировании сложного React-приложения.

```

2023-04-26 00:08 UTC, gcor commented on src/content/learn/installation.md
> +* [Как создать новый React проект](/learn/start-a-new-react-project)
```suggestion
* [Как создать новый проект на React](/learn/start-a-new-react-project)

```

2023-04-26 00:08 UTC, gcor commented on src/content/learn/installation.md
> +* [Как добавить React в уже существующий проект](/learn/add-react-to-an-existing-project)
```suggestion
* [Как добавить React в существующий проект](/learn/add-react-to-an-existing-project)

```

2023-04-26 00:08 UTC, gcor commented on src/content/learn/installation.md
> +Такие песочницы есть на большинстве страниц React документации. За пределами React документации также есть большое количество песочниц, поддерживающих React. Например: [CodeSandbox](https://codesandb
"документации React" или "React-документации"
Проверьте пожалуйста и в других местах пропущенный дефис

2023-04-26 00:08 UTC, gcor commented on src/content/learn/installation.md
> +## Начать новый React проект {/*start-a-new-react-project*/}
Предлагаю "проекта на React"
тут и ниже

2023-04-26 12:47 UTC, ntishkevich requested changes

2023-04-26 12:47 UTC, ntishkevich commented on src/content/learn/installation.md
Обратите внимание на переносы строк в вашем файле. В оригинале `LF`, а у вас `CRLF`, поэтому diff этого файла весь красный и зеленый и git считает, что вы удалили контент и вновь его написали, а должен быть diff построчный, что позволит избежать большого количества конфликтов из-за неверных переносов.

Поэтому, просьба настроить свой редактор кода или IDE на работу с переносами из этого проекта.

2023-04-26 12:47 UTC, ntishkevich commented on src/content/learn/installation.md
> +## Начать новый React проект {/*start-a-new-react-project*/}
Этот перевод пересекается с #850. Предлагаю определиться с именованием. Могу предложить `Начать новый React-проекта`

2023-05-18 20:15 UTC, ntishkevich requested changes
Спасибо за перевод. Небольшие комментарии.

Также хочу обратить внимание, что переводить файлы типа sideBar.json, MDXComponents.txs, ResetButton.tsx согласно описанию из ишью #843 нужно в последнюю очередь из всего списка для перевода.

2023-05-19 11:44 UTC, Palidos commented on src/content/learn/installation.md
> +Что бы поиграть с React локально на вашем компьютере, [скачайте эту HTML страницу.](https://gist.githubusercontent.com/gaearon/0275b1e1518599bbeafcde4722e79ed1/raw/db72dcbf3384ee1708c4a07d3be79860db0
Удалил перевод UI элементов и применил исправления из комментариев

2023-05-19 12:25 UTC, ntishkevich approved these changes
LGTM

2023-05-19 15:58 UTC, fpetrakov reviewed
Привет, спасибо за перевод, есть предложения, что думаешь?

2023-05-19 15:58 UTC, fpetrakov commented on src/content/learn/installation.md
> +Чтобы попробовать React, даже устанавливать ничего не нужно. Редактируйте прямо в песочнице!
```suggestion
Вам не нужно ничего устанавливать, чтобы попробовать React. Поредактируйте код в песочнице!
```

Кажется, что черезчур игриво

> Редактируйте прямо в песочнице

А где `try`?

2023-05-19 17:54 UTC, Palidos commented on src/content/learn/installation.md
> +Чтобы попробовать React, даже устанавливать ничего не нужно. Редактируйте прямо в песочнице!
Да, с "Поредактируйте" приятнее, но что координально меняется при изменении порядка слов?

2023-05-19 18:17 UTC, Palidos commented on src/content/learn/installation.md
> +Перейдите к [Введению в React](/learn) для ознакомления с самыми важными его концепциями, с которыми вы будете сталкиваться каждый день.
Не могу сказать, что объективно, но ладно.

2023-05-20 09:04 UTC, ntishkevich commented on src/content/learn/installation.md
> +React был спроектирован с самого начала с учётом постепенного внедрения. Вы можете начать с малого и использовать только ту функциональность React, которая необходима вам в данный момент. Информация
Текущий вариант читается лучше, чем предложенный.

2023-05-20 14:00 UTC, fpetrakov commented on src/content/learn/installation.md
> +Чтобы попробовать React, даже устанавливать ничего не нужно. Редактируйте прямо в песочнице!
>  "Поредактируйте" приятнее

Оно там не для приятности, а чтобы `to try` перевести, которое не было переведено

> что координально меняется при изменении порядка слов

Я выкинул "даже", потому что его нет в оригинале, стало так: "Чтобы попробовать React, устанавливать ничего не нужно", поменял порядок слов, чтобы звучало естественнее на русском и при этом ближе к оригиналу

2023-05-20 14:03 UTC, fpetrakov commented on src/content/learn/installation.md
> +Перейдите к [Введению в React](/learn) для ознакомления с самыми важными его концепциями, с которыми вы будете сталкиваться каждый день.
> Не могу сказать, что объективно, но ладно.

В данном случае и не претендую, просто предложение

2023-05-21 23:37 UTC, gcor approved these changes

2023-05-21 23:37 UTC, gcor commented on src/content/learn/installation.md
> +Чтобы попробовать React, даже устанавливать ничего не нужно. Поредактируйте код в песочнице!
```suggestion
Вам не нужно ничего устанавливать, чтобы попробовать React. Поредактируйте код в песочнице!
```

2023-05-22 19:50 UTC, ntishkevich commented on src/content/learn/installation.md
> +Перейдите к [Введению в React](/learn) для ознакомления с самыми важными его концепциями, с которыми вы будете сталкиваться каждый день.
@Palidos, получилось сложнее и появилась (забыли добавить) запятая, а у нас уже есть одна перед "которые". Можно упростить, взяв вариант
```
Перейдите к [Введению в React](/learn) для ознакомления с самыми важными концепциями, которые вы будете встречать каждый день.
```

@fpetrakov, "важнейшими" не подходит, раз вы ставили цель избавление от кучи шипящих - получилось наоборот. Плюс не понятно "его" это относится к чему? Реакт - библиотека, тогда будет должно быть "её"? Поэтому предлагаю свой вариант.

2023-05-22 20:07 UTC, merged