conditional-rendering.md ru
reactjs/ru.react.dev pull request #844
Opened 2023-04-25 11:40 UTC by rainyEra

Правила прочитал.
Ошибки исправил.
Проверил на работоспособность.

2023-04-25 18:03 UTC, XamzatJR commented on src/content/learn/conditional-rendering.md
> +Вашим компонентам нужно часто отображать различные вещи в зависимости от различных условий. В React вы можете реденрить JSX в зависимости от его условий, используя JavaScript операторы. Такие, как `i
забыли "н" в слове "рендерить"

2023-04-25 23:42 UTC, rainyEra commented on src/content/learn/conditional-rendering.md
> +Вашим компонентам нужно часто отображать различные вещи в зависимости от различных условий. В React вы можете реденрить JSX в зависимости от его условий, используя JavaScript операторы. Такие, как `i
> забыли "н" в слове "рендерить"

Спасибо, исправил.

2023-04-26 21:37 UTC, fpetrakov reviewed
Привет, спасибо, посмотрел немного перевод, есть предложения, что думаешь?

2023-04-26 21:37 UTC, fpetrakov commented on src/content/learn/conditional-rendering.md
> +Допустим, у вас есть `PackingList` компонент, который рендерит несколько `Item`, которые могут быть обозначены, как упакованные или неупавкованные:
2 раза подряд "который", кажется, можно поправить. 

```suggestion
Допустим, у вас есть компонент `PackingList`, который рендерит несколько компонентов `Item`, они могут быть обозначены, как упакованные или нет:
```

В английском нормально просто написать "several `Item`s", потому что компонент назван по английски, в русском могло быть что-то типа такого "который рендерит несколько `Вещей`". Но т.к. мы тоже называем компоненты по английски, то стоит добавить "компонентов", чтобы фраза не звучала обрывочно

2023-04-26 21:37 UTC, fpetrakov commented on src/content/learn/conditional-rendering.md
> +Заметь, что некоторые `Item` компоненты имеют свой `isPacked` проп, который `true` вместо `false`. Вы хотите добавить галочку (✔) к упакованным вещам, если if `isPacked={true}`.
> Заметь
Т.к. мы с читателем на "вы", а "заметьте" сложно выговаривается, то предлагаю "Обратите внимание"

```suggestion
Обратите внимание, что некоторые компоненты `Item` имеют свойство `isPacked`, со значением `true` вместо `false`. Допустим, вы хотите добавить (✔) к упакованным вещам, если if `isPacked={true}`.
```
или
```suggestion
Обратите внимание, что некоторые компоненты `Item` имеют свойство `isPacked`, со значением `true` вместо `false`. Вам необходимо добавить (✔) к упакованным вещам, если if `isPacked={true}`.
```

2023-04-26 21:37 UTC, fpetrakov commented on src/content/learn/conditional-rendering.md
> +Вы можете писать это как [`if`/`else` условие](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/if...) таким образом:
```suggestion
Можно реализовать это с помощью [управляющей конструкции `if`/`else`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/if...) таким образом:
```

2023-04-26 21:37 UTC, fpetrakov commented on src/content/learn/conditional-rendering.md
> +Вы можете писать это как [`if`/`else` условие](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/if...) таким образом:
statement это все-таки управляющая конструкция, ну или инструкция, как переведено на прекрепленном здесь же mdn

2023-04-26 21:37 UTC, fpetrakov commented on src/content/learn/conditional-rendering.md
> +- Как условно включить или исключить фрагмент JSX
Как по условию добавить или убрать часть JSX

2023-04-26 21:37 UTC, fpetrakov commented on src/content/learn/conditional-rendering.md
> +- Общий условный синтаксис, который вы встретите в кодовой базе React.
```suggestion
- Часто встречающиеся конструкции, которые вы найдете в проектах на React  
```

2023-04-26 22:23 UTC, rainyEra commented
> Привет, спасибо, посмотрел немного перевод, есть предложения, что думаешь?

Привет, отличные предложения! Только не согласен по поводу React и JSX. React - библиотека, JSX - объекты под капотом. Читатель знакомиться с JSX до этого момента, поэтому не вижу противоречий. React то рендерит JSX — о чем контекст текста.

Спасибо!!

2023-04-26 22:46 UTC, rainyEra commented on src/content/learn/conditional-rendering.md
> +- Как условно включить или исключить фрагмент JSX
я добавил это предложение, но разве первый вариант для русского человек не звучит лучше? меня просто "условно" немного напрягает и "в зависимости от условия" звучало бы лучше, не?

2023-04-27 07:56 UTC, fpetrakov commented on src/content/learn/conditional-rendering.md
> +- Как условно включить или исключить фрагмент JSX
> в зависимости от **его** условия

Тут просто не понятно из контекста про чьи условия идет речь. Мне тоже не нравится "условно", можно "по условию" или "в зависимости от ситуации", например так:

- Как вернуть разный JSX, в зависимости от ситуации
- Как по условию добавить или убрать часть JSX

2023-04-27 09:42 UTC, rainyEra commented on src/content/learn/conditional-rendering.md
> +- Как условно включить или исключить фрагмент JSX
> > в зависимости от **его** условия
> 
> Тут просто не понятно из контекста про чьи условия идет речь, в оригинале также нет указания на **чьи** то условия. Поэтому, возможно, и переводили как "условный рендеринг", но мне тоже не нравится "условно", можно "по условию" или "в зависимости от ситуации", например так:
> 
> * Как вернуть разный JSX, в зависимости от ситуации
> * Как по условию добавить или убрать часть JSX

Сделал правку, благодарю!

2023-05-21 21:45 UTC, gcor commented
@rainyEra, пожалуйста решите конфликт в ветке)

2023-05-22 04:27 UTC, rainyEra commented
> @rainyEra, пожалуйста решите конфликт в ветке)

@gcor Добрый день, какой конфликт? 

- Использование чистых компонентов - на данный момент нет открытого пулл-реквеста

Я не брал эту работу, ей должен был заниматься другой человек.

2023-05-22 04:48 UTC, rainyEra commented
> @rainyEra, пожалуйста решите конфликт в ветке)

Спасибо, исправил!

2023-05-22 19:34 UTC, ntishkevich requested changes
Спасибо за ваш перевод. Есть ряд комментарием

2023-05-22 19:34 UTC, ntishkevich commented on src/content/learn/conditional-rendering.md
> +В этом решении, два раздельных условия были использованы, чтобы вставить пробел между именем и меткой важности. В качестве альтернативы можно использовать фрагмент с ведущим пробелом: `importance > 0
```suggestion
В этом решении используются два отдельных условия для вставки пробела между именем и меткой важности. Кроме того, можно использовать фрагмент с ведущим пробелом: `importance > 0 && <> <i>...</i></>` или добавить пробел сразу внутри тега `<i>`: `importance > 0 && <i> ...</i>`.
```
Перефразировал и избавился от запятых ненужных.

2023-05-22 19:34 UTC, ntishkevich commented on src/content/learn/conditional-rendering.md
> +#### Перепешите тернарный оператор `? :` на `if` с переменной {/*refactor-a-series-of---to-if-and-variables*/}
```suggestion
#### Перепишите тернарный оператор `? :` на `if` и переменные {/*refactor-a-series-of---to-if-and-variables*/}
```
Орфографию поправил, плюс в оригинале множественное число

2023-05-22 19:34 UTC, ntishkevich commented on src/content/learn/conditional-rendering.md
> +Этот `Drink` компонент использует серию `? :` условий, чтобы показать разную информацию, которая зависит от `name` пропа, который `"tea"` или `"coffee"`. Проблема в том, что информация о каждом напит
```suggestion
Компонент `Drink` использует серию условий `? :` для отображения разной информацию в зависимости от пропа `name` (может быть `"tea"` или `"coffee"`). Проблема заключается в том, что информация о каждом напитке разбросана по нескольким условиям. Перепишите этот код так, используя один `if` вместо трёх условий `? :`.
```
Перефразировал, исправил ошибки

2023-05-22 19:34 UTC, ntishkevich commented on src/content/learn/conditional-rendering.md
> +После рефакторинга кода с использованием `if` у вас есть идеи, как его упростить?
```suggestion
После рефакторинга кода с использованием `if`, у вас есть ещё идеи о том, как упростить его?
```
Перефразировал и добавил нужную запятую.

2023-05-22 19:34 UTC, ntishkevich commented on src/content/learn/conditional-rendering.md
> +Здесь информация о каждом напитке сгруппирована вместе, а не распределена по нескольким условиям. Это облегчает добавление новых напитков в будущем.
```suggestion
Здесь информация о каждом напитке сгруппирована вместе, а не разбросана по нескольким условиям. Это облегчает добавление новых напитков в будущем.
```
Перефразировал, "разбросана", имхо, лучше подходит здесь.

2023-05-22 19:34 UTC, ntishkevich commented on src/content/learn/conditional-rendering.md
> +Другим решением может быть полное удаление условий путем перемещения информации в объекты:
```suggestion
Другим решением будет удалить условия, переместив информацию в объекты:
```
Перефразировал и упростил, читать стало проще

2023-05-22 20:28 UTC, rainyEra commented on src/content/learn/conditional-rendering.md
> +#### Являются ли эти два примера полностью эквивалентными? {/*are-these-two-examples-fully-equivalent*/}
Кажется, что первый вариант передает лучше ключевой смысл, не?

2023-05-22 20:30 UTC, ntishkevich commented on src/content/learn/conditional-rendering.md
> +#### Являются ли эти два примера полностью эквивалентными? {/*are-these-two-examples-fully-equivalent*/}
Смысл одинаковый, разница в лишнем слове в заголовке

2023-05-22 21:05 UTC, rainyEra commented on src/content/learn/conditional-rendering.md
> +## Условно возвращаемый JSX {/*conditionally-returning-jsx*/}
```suggestion
## Условный возврат JSX {/*conditionally-returning-jsx*/}
```

2023-05-22 21:08 UTC, rainyEra commented
> Спасибо за ваш перевод. Есть ряд комментарием

Большое спасибо. Кавычки заменил, пробелы удалил и предложения принял.

2023-05-23 08:36 UTC, ntishkevich requested changes
Сделал вычитку после правок, небольшие комментарии и в целом можно будет мержить.

2023-05-23 08:36 UTC, ntishkevich commented on src/content/learn/conditional-rendering.md
> +Если вы знакомы с объектно-ориентированным программированием, вы можете предположить, что два приведенных выше примера немного отличаются друг от друга, поскольку один из них может создавать два разн
```suggestion
Если вы знакомы с объектно-ориентированным программированием, вы можете предположить, что два приведенных выше примера немного отличаются друг от друга, поскольку один из них может создавать два разных "экземпляра" `<li>`. Но JSX-элементы не являются "экземплярами", потому что они не хранят никакого внутреннего состояния и не являются реальными DOM-узлами. Это лёгкие описания, как чертежи. На самом деле эти два примера *совершенно эквивалентны*. В [Сохранение и сброс состояния](/learn/preserving-and-resetting-state) подробно рассказывается о том, как это работает.
```
У меня в предложенном варианте была ошибка с лишним пробелом. Исправляю.

2023-05-23 08:36 UTC, ntishkevich commented on src/content/learn/conditional-rendering.md
> +[Фигурные скобки открывают "окно в мир JavaScript".](/learn/javascript-in-jsx-with-curly-braces#using-curly-braces-a-window-into-the-javascript-world) Вставьте переменную с фигурными скобками в возвр
```suggestion
[Фигурные скобки открывают "окно в мир JavaScript".](/learn/javascript-in-jsx-with-curly-braces#using-curly-braces-a-window-into-the-javascript-world) Вставьте переменную с помощью фигурных скобок в возвращаемое дерево JSX, вложив ранее вычисленное выражение внутрь JSX:
```
Слегка перефразировал, сейчас более понятно причём тут фигурные скобки.

2023-05-27 10:23 UTC, ntishkevich approved these changes
LGTM

2023-05-27 10:23 UTC, ntishkevich approved these changes
LGTM

2023-06-15 12:26 UTC, ntishkevich commented
@gcor как будет время, посмотри плиз

2023-07-05 19:13 UTC, merged