Rutranslation/quick start
reactjs/ru.react.dev pull request #846
Opened 2023-04-25 19:49 UTC by pblyp

**Если ваш пулреквест является исправлением бага, а не переводом, то сперва убедитесь, что проблема относится ТОЛЬКО к https://ru.reactjs.org, а не к https://reactjs.org.** Если это не так, то пулреквест следует открыть в родительском репозитории.

2023-04-26 00:46 UTC, gcor reviewed
Спасибо большое! 👍 

Вот такие комментарии и предложения:

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +Добро пожаловать в документацию React! Эта страница посвятит вас в основы 80% концепций React, которыми вы будете пользоваться каждый день.
```suggestion
Добро пожаловать в документацию React! Эта страница познакомит вас с большинством концепций React, которыми вы будете пользоваться каждый день.
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +- Как реагировать на события и обновлять экран
как будто слово экран сложно ложиться)
может быть
```suggestion
- Как реагировать на события и обновлять страницу
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +Приложения на React собираются из *компонентов*. Компонент — это часть пользовательского интерфейса, у которой есть свои логика и внешность. Компоненты в размерах разнятся от мелких кнопок до больших
```suggestion
Приложения на React собираются из *компонентов*. Компонент — это часть пользовательского интерфейса, у которого есть собственная логика и внешность. Компонент может быть маленьким, как кнопка, или большим, как целая страница.
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +Используемый в примерах выше синтаксис разметки называется *JSX*. Он не обязателен, но большинство проектов на React предпочитают его использовать за удобство. Все [инструменты, которые мы рекомендуе
```suggestion
Синтаксис разметки, который вы видели выше, называется *JSX*. Он не обязателен, но большинство проектов на React предпочитают его использовать из-за удобства. Все [инструменты, которые мы рекомендуем для локальной разработки,](/learn/installation) поддерживают JSX.
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +В отдельном CSS-файле вы прописываете стили для него.
```suggestion
В отдельном CSS-файле вы прописываете для него стили. 
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +JSX позволяет вам встраивать разметку в JavaScript, а фигурные скобки позволяют вам "выйти" в JavaScript для того, чтобы вы могли встроить какую-либо переменную из вашего кода и показать ее пользоват
```suggestion
Фигурные скобки внутри JSX-разметки позволяют использовать JavaScript, например для того чтобы отобразить свою переменную пользователю. Код ниже отобразит `user.name`:
```

Поскольку раздел про отображение данных, позволил себе чуть упростить первое предложение про то что JSX работает в JS. Информация  о том, что такое JSX уже есть раньше.

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +Вы тажке можете "выйти в JavaScript" из атрибутов JSX, но вам нужно использовать фигурные скобки *вместо* кавычек. Например, `className="avatar"` передает строку `"avatar"` как класс CSS, но `src={us
```suggestion
Вы также можете использовать JavaScript а атрибутах JSX. В таком случае вам нужно поставить фигурные скобки *вместо* кавычек. Например, `className="avatar"` передает строку `"avatar"` как CSS-класс, а `src={user.imageUrl}` считывает значение JavaScript-переменной `user.imageUrl` и передает его в качестве атрибута `src`:
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +Вы также можете прописывать более сложные выражения внутри фигурных скобок JSX, например, [сложение строк](https://learn.javascript.ru/operators#slozhenie-strok-pri-pomoschi-binarnogo):
```suggestion
Вы также можете использовать в JSX более сложные выражения внутри фигурных скобок, например, [сложение строк](https://learn.javascript.ru/operators#slozhenie-strok-pri-pomoschi-binarnogo):
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +В этом примере `style={{}}` не явлется особым синтаксисом, а представляет из себя обычный объект `{}` внутри фигурных скобок JSX `style={ }`. Вы можете использовать атрибут `style` в случаях, когда в
```suggestion
В этом примере `style={{}}` не является специальным синтаксисом, а представляет из себя обычный объект `{}` внутри фигурных скобок JSX `style={ }`. Вы можете использовать атрибут `style` в случаях, когда ваши стили зависят от переменных JavaScript.
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +В React не существует особого синтаксиса для описания условий, вместо этого пишите привычный вам код на JavaScript. Например, для условного использования JSX-кода можно применять инструкцию [`if`](ht
```suggestion
В React не существует специального синтаксиса для описания условий, вместо этого можно использовать обычный код на JavaScript. Например, для условного рендреринга JSX-кода можно применять [`if`](https://developer.mozilla.org/ru-RU/docs/Web/JavaScript/Reference/Statements/if...else):
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +Все эти способы подходят и для условного задания атрибутов. Если вам не знакомы такие синтаксические конструкции JavaScript, вы можете начать с повсеместного использования `if...else`.
```suggestion
Все эти способы подходят и для задания условий в атрибутах. Если вам не знакомы такие синтаксические конструкции JavaScript, вы можете начать с использования `if...else`.
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +Можно реагировать на события, объявляя внутри ваших компонентов функции *обработчиков событий*:
```suggestion
Вы можете реагировать на события, объявляя внутри ваших компонентов функции *обработчиков событий*:
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +`useState` вернет вам две сущности: текущее состояние (`count`) и функцию (`setCount`), которая обновляет его. Можно назвать их как вам угодно, но такого рода вещи принято называть `[something, setSo
```suggestion
`useState` вернет вам две вещи: текущее состояние (`count`) и функцию (`setCount`), которая обновляет его. Можно именовать их как вам угодно, но такого рода вещи принято называть `[something, setSomething]`.
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +На первый показ кнопки `count` будет иметь значение `0`, потому что вы передали `0` в `useState()`. Когда вы хотите изменить состояние, вызовите `setCount()` и передайте туда новое значение. Клик на
```suggestion
При первом показе кнопка `count` будет иметь значение `0`, потому что вы передали `0` в `useState()`. Чтобы изменить состояние, вызовите `setCount()` и передайте туда новое значение. Клик на эту кнопку будет увеличивать счётчик:
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +При клике `MyApp` обновляет своё состояние `count` значением `1` и передает его вниз обоим потомкам
```suggestion
При клике `MyApp` обновляет своё состояние `count` на значение `1` и передает его вниз обоим потомкам
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +Теперь вы знаете, как писать простой код для React!
```suggestion
Теперь вы знаете основы, как писать код для React!
```

2023-04-26 00:46 UTC, gcor commented on src/content/learn/index.md
> +Ознакомьтесь с [введением](/learn/tutorial-tic-tac-toe), в рамках которого вы примените полученные знания и соберёте свое первое мини-приложение на React.
```suggestion
Ознакомьтесь с [введением](/learn/tutorial-tic-tac-toe), в рамках которого вы сможете применить полученные знания и собрать своё первое мини-приложение на React.
```

2023-04-26 07:49 UTC, pblyp commented on src/content/learn/index.md
> +Вы тажке можете "выйти в JavaScript" из атрибутов JSX, но вам нужно использовать фигурные скобки *вместо* кавычек. Например, `className="avatar"` передает строку `"avatar"` как класс CSS, но `src={us
```suggestion
Вы также можете использовать JavaScript в атрибутах JSX. В таком случае вам нужно поставить фигурные скобки *вместо* кавычек. Например, `className="avatar"` передает строку `"avatar"` как CSS-класс, а `src={user.imageUrl}` считывает значение JavaScript-переменной `user.imageUrl` и передает его в качестве атрибута `src`:
```

2023-04-26 07:50 UTC, pblyp commented on src/content/learn/index.md
> +В React не существует особого синтаксиса для описания условий, вместо этого пишите привычный вам код на JavaScript. Например, для условного использования JSX-кода можно применять инструкцию [`if`](ht
"рендеринга"
```suggestion
В React не существует специального синтаксиса для описания условий, вместо этого можно использовать обычный код на JavaScript. Например, для условного рендеринга JSX-кода можно применять [`if`](https://developer.mozilla.org/ru-RU/docs/Web/JavaScript/Reference/Statements/if...else):
```

2023-04-26 07:52 UTC, pblyp commented on src/content/learn/index.md
> +При клике `MyApp` обновляет своё состояние `count` значением `1` и передает его вниз обоим потомкам
"передаёт", прошляпил, прошу прощения
```suggestion
При клике `MyApp` обновляет своё состояние `count` значением `1` и передает его вниз обоим потомкам
```

2023-04-26 07:59 UTC, pblyp commented
Антон, спасибо за то, что потратили на меня время и очень быстро ответили! Впервые за очень долгое время перевел что-то техническое, очень нравится, когда быстро реагируют на твои предложения)

2023-04-26 23:03 UTC, gcor reviewed
Еще немного правок после повторного прочтения :)

2023-04-26 23:03 UTC, gcor commented on src/content/learn/index.md
> +Теперь вы знаете основы, как писать код для React!
```suggestion
Теперь вы знаете основы того, как писать код для React!
```

2023-05-02 11:31 UTC, ntishkevich requested changes
Спасибо за перевод. Вот еще несколько моментов, которые можно исправить.

2023-05-02 11:31 UTC, ntishkevich commented on src/content/learn/index.md
> +Функции, которые начинаются с `use`, называются *хуками*. `useState` — это встроенный в React хук. В [справочнике API](/reference/react) приводятся другие встроенные хуки. Также, вы можете писать сво
```suggestion
Функции, которые начинаются с `use`, называются *хуками*. `useState` — это встроенный хук в React. В [справочнике API](/reference/react) приводятся другие встроенные хуки. Также, вы можете писать свои собственные хуки, совмещая их с уже существующими.
```
Мне кажется с таким порядком слов предложение звучит лучше. Что скажите?

2023-05-02 11:31 UTC, ntishkevich commented on src/content/learn/index.md
> +<Diagram name="sharing_data_child" height={367} width={407} alt="Диаграмма, показывающая дерево из трех компонентов, состоящее из компонента-родителя под названием MyApp и двух дочерних компонентов п
```suggestion
<Diagram name="sharing_data_child" height={367} width={407} alt="Диаграмма, показывающая дерево из трёх компонентов, состоящее из компонента-родителя под названием MyApp и двух дочерних компонентов под названием MyButton. Оба компонента MyButton содержат счётчик со значением, равным нулю.">
```
ё

2023-05-02 11:31 UTC, ntishkevich commented on src/content/learn/index.md
> +Теперь, когда вы нажимаете на любую из кнопок, `count` в `MyApp` будет менять своё значение, что в свою очередь повлечёт обновление счётчиков в обоих компонентах `MyButton`. Вот как это можно прописа
```suggestion
Теперь, когда вы нажимаете на любую из кнопок, `count` в `MyApp` будет менять своё значение, что в свою очередь повлечёт обновление счётчиков в обоих компонентах `MyButton`. Вот как это можно выразить в коде.
```
Я бы заменил слово "прописать" на "выразить"

2023-05-02 11:31 UTC, ntishkevich commented on src/content/learn/index.md
> +Когда вы нажимаете на кнопку, срабатывает обработчик `onClick`. В каждой кнопке в качестве значения пропа `onClick` задана функция `handleClick` из `MyApp`, таким образом, исполняется код этой функци
```suggestion
Когда вы нажимаете на кнопку, срабатывает обработчик `onClick`. В каждой кнопке в качестве значения пропа `onClick` задана функция `handleClick` из `MyApp`, таким образом, исполняется код этой функции. Этот код вызывает `setCount(count + 1)`, тем самым увеличивая переменную состояния `count`. Новое значение `count` передаётся в качестве пропа каждой кнопке, таким образом все кнопки будут показывать это новое значение. Это называется "подъёмом состояния вверх". Поднимая состояние вверх, вы делаете его общим для всех компонентов.
```
ё

2023-05-04 07:57 UTC, pblyp commented
Просмотрел вроде бы все предложения, спасибо! Посмотрите, пожалуйста, что я еще не закрыл из них.

2023-05-18 20:04 UTC, ntishkevich commented
> Просмотрел вроде бы все предложения, спасибо! Посмотрите, пожалуйста, что я еще не закрыл из них.

@pblyp пропустили 3 комментария:
- Первый https://github.com/reactjs/ru.react.dev/pull/846#discussion_r1181826705
- Второй https://github.com/reactjs/ru.react.dev/pull/846#discussion_r1182225202
- Третий https://github.com/reactjs/ru.react.dev/pull/846#discussion_r1182243324

2023-06-14 19:37 UTC, pblyp commented
@ntishkevich четвертый коммент принял, по остальным у меня остались те же вопросы, посмотрите на них, пожалуйста, мои предложения висят в pending и без четкого согласия не хочу их сливать сам

> Первый https://github.com/reactjs/ru.react.dev/pull/846#discussion_r1178473667
> Второй https://github.com/reactjs/ru.react.dev/pull/846#discussion_r1181826705
> Третий https://github.com/reactjs/ru.react.dev/pull/846#discussion_r1182225202

2023-06-14 19:48 UTC, ntishkevich commented
> по остальным у меня остались те же вопросы, посмотрите на них, пожалуйста, мои предложения висят в pending и без четкого согласия не хочу их сливать сам

Если они висят в пендинг, то вы их не опубликовали и кроме вас их никто не видит, поэтому ваших предложений не видел ни я, ни @gcor. Опубликуйте их и мы сможем   их посмотреть.

2023-06-14 21:20 UTC, pblyp commented
https://github.com/orgs/community/discussions/10369#discussion-3815011
Извините, крайне неочевидный момент был для меня, учитывая мой скромный опыт работе с GitHub

2023-06-15 11:58 UTC, ntishkevich commented on src/content/learn/index.md
> +Информация, которую вы передаёте таким образом, называется _пропсами_. Теперь у компонента `MyApp` есть состояние `count` и обработчик событий `handleClick`, *которые он передает в качестве пропсов*
Отлично, что вы заметили пропущенное нами `ё`

2023-06-15 12:03 UTC, ntishkevich commented on src/content/learn/index.md
> +В React CSS-классы объявляются с помощью свойства `className`. Оно работает аналогично HTML-аттрибуту [`class`](https://developer.mozilla.org/ru-RU/docs/Web/HTML/Global_attributes/class):
Отлично, что вы заметили опечатку в слове `атрибут`

2023-06-15 12:14 UTC, ntishkevich commented on src/content/learn/index.md
> +React не ограничивает вас в том, как добавлять CSS-файлы. В самом простом случае вы добавляете тэг [`<link>`](https://developer.mozilla.org/ru-RU/docs/Web/HTML/Element/link) в ваш HTML-файл. Если вы
Хорошо, что вы заметили нехватку запятой, смело добавляйте её.

2023-06-15 12:15 UTC, ntishkevich commented
Довольно странно, но на некоторые ваши комментарии не могу сделать реплай 😲 

@pblyp Прочитал все ваши комментарии. Где мог оставить коммент, я оставил. Остальные комменты я осветил здесь.
Касаемо ["оставить слово свойство"](https://github.com/reactjs/ru.react.dev/pull/846#discussion_r1184635678), то я бы не оставлял, это может вызвать путаницу между свойством `className` у `HTMLElement` и атрибутом `className` у React-элемента.

В вашем [предложении ](https://github.com/reactjs/ru.react.dev/pull/846#discussion_r1184652439) мне нравится первый предложенный вариант. Можем использовать его.

По поводу [строчки 493](https://github.com/reactjs/ru.react.dev/pull/846#discussion_r1178836779). Согласен, что звучит сложно, но выкидывать предложения не стоит. Я могу предложить  такой вариант перевода:
```
При нажатии на кнопку срабатывает обработчик `onClick`. Каждой кнопке в качестве значения пропа `onClick` задана функция `handleClick` из `MyApp`, поэтому выполняется соответствующий код. Этот код вызывает функцию `setCount(count + 1)`, увеличивая значение состояния `count`. Новое значение `count` передается каждой кнопке  качестве пропа, поэтому они все отображают новое значение. Это называется "подъёмом состояния вверх". Поднимая состояние вверх, вы делаете его общим для всех компонентов.
```
Избавимся от словосочетаний "таким образом" и используем предложенный вами вариант с "функцией".

2023-06-18 09:49 UTC, pblyp commented
@ntishkevich надеюсь, справился с замечаниями

2023-06-18 13:43 UTC, ntishkevich approved these changes
LGTM, но просьба поправить небольшое замечание - пропустили `ё`.

2023-06-18 13:43 UTC, ntishkevich commented on src/content/learn/index.md
> +При нажатии на кнопку срабатывает обработчик `onClick`. Каждой кнопке в качестве значения пропа `onClick` задана функция `handleClick` из `MyApp`, поэтому выполняется соответствующий код. Этот код вы
```suggestion
При нажатии на кнопку срабатывает обработчик `onClick`. Каждой кнопке в качестве значения пропа `onClick` задана функция `handleClick` из `MyApp`, поэтому выполняется соответствующий код. Этот код вызывает функцию `setCount(count + 1)`, увеличивая значение состояния `count`. Новое значение `count` передаётся каждой кнопке в качестве пропа, поэтому они все отображают новое значение. Это называется "подъёмом состояния вверх". Поднимая состояние вверх, вы делаете его общим для всех компонентов.
```

2023-06-18 13:43 UTC, ntishkevich commented
@gcor посмотри, плиз, как будет время.

2023-07-05 19:22 UTC, gcor approved these changes

2023-07-05 19:29 UTC, merged