Translate reference/useId
reactjs/ru.react.dev pull request #856
Opened 2023-04-27 23:07 UTC by mekarthedev

#843

2023-04-30 00:38 UTC, rainyEra requested changes
Привет, просмотрел, что думаешь?

2023-04-30 00:38 UTC, rainyEra commented on src/content/reference/react/useId.md
> +* `useId` -- это хук. Поэтому его можно вызывать только **на верхнем уровне кода вашего компонента** или хука. Его нельзя вызывать внутри циклов и условий. Если это всё же для чего-то нужно, выделите
```suggestion
* `useId` — это хук, поэтому его можно вызывать только **на верхнем уровне вашего компонента** или вашего хука. Его нельзя вызывать внутри циклов и условий. Если это всё же для чего-то нужно, выделите этот вызов в отдельный компонент, который затем можно рендерить по условию или в цикле.
```

2023-04-30 00:38 UTC, rainyEra commented on src/content/reference/react/useId.md
> +Чтобы получить уникальный идентификатор, вызовите `useId` на верхнем уровне своего компонента:
```suggestion
Чтобы получить уникальный идентификатор, вызовите `useId` на верхнем уровне вашего компонента:
```

2023-04-30 00:38 UTC, rainyEra commented on src/content/reference/react/useId.md
> +После чего вы можете указывать этот <CodeStep step={1}>сгенерированный идентификатор</CodeStep> в различных атрибутах:
```suggestion
После чего вы можете указывать этот <CodeStep step={1}> сгенерированный идентификатор</CodeStep> в различных атрибутах:
```

2023-04-30 00:38 UTC, rainyEra commented on src/content/reference/react/useId.md
> +Однако в React подобным образом фиксировать идентификаторы в коде -- не лучшая практика. Один и тот же компонент может использоваться в нескольких разных местах -- но ведь в каждом случае идентификат
```suggestion
Однако в React подобным образом фиксировать идентификаторы в коде — не лучшая практика. Один и тот же компонент может использоваться в нескольких разных местах — но ведь в каждом случае идентификаторы должны быть уникальны! Поэтому вместо фиксированного идентификатора лучше сгенерировать уникальный с помощью `useId`:
```

2023-04-30 00:38 UTC, rainyEra commented on src/content/reference/react/useId.md
> +Возможно вы задаётесь вопросом, почему лучше использовать `useId`, а не просто постоянно увеличивать некий глобальный счётчик -- наподобие `nextId++`.
```suggestion
Возможно, вы задаётесь вопросом, почему лучше использовать `useId`, а не постоянно увеличивать глобальный счётчик — наподобие `nextId++`.
```

2023-04-30 00:38 UTC, rainyEra commented on src/content/reference/react/useId.md
> +`useId` -- хук для генерации уникальных идентификаторов, которые можно использовать, например, в атрибутах доступности.
```suggestion
`useId` — это хук для генерации уникальных идентификаторов, которые можно использовать, например, в атрибутах доступности.
```

2023-04-30 00:38 UTC, rainyEra commented on src/content/reference/react/useId.md
> +Чтобы создать уникальный идентификатор, вызовите `useId` на верхнем уровне своего компонента:
```suggestion
Чтобы создать уникальный идентификатор, вызовите `useId` на верхнем уровне компонента:
```

2023-04-30 00:38 UTC, rainyEra commented on src/content/reference/react/useId.md
> +Возможно вы задаётесь вопросом, почему лучше использовать `useId`, а не просто постоянно увеличивать некий глобальный счётчик -- наподобие `nextId++`.
вводное слово

2023-04-30 09:43 UTC, mekarthedev commented on src/content/reference/react/useId.md
> +После чего вы можете указывать этот <CodeStep step={1}>сгенерированный идентификатор</CodeStep> в различных атрибутах:
А для чего этот пробел?

2023-04-30 09:47 UTC, mekarthedev commented on src/content/reference/react/useId.md
> +Однако в React подобным образом фиксировать идентификаторы в коде -- не лучшая практика. Один и тот же компонент может использоваться в нескольких разных местах -- но ведь в каждом случае идентификат
А почему так лучше? Двойной даш тут и повсеместно в оригинале – это более удобный в наборе специальный синтаксис, превращающийся автоматом в em dash.

2023-04-30 11:20 UTC, mekarthedev commented on src/content/reference/react/useId.md
> +Чтобы получить уникальный идентификатор, вызовите `useId` на верхнем уровне своего компонента:
Не соглашусь. Возвратно-притяжательное предпочтительнее, если нет акцента именно на принадлежности. Можно для проверки, например, вот так видоизменить фразу: "вы можете получать идентификаторы в ваших компонентах" – и смысловая неоднозначность становится виднее по сравнению с "вы можете получать идентификаторы в своих компонентах". Типа как "ты живешь в твоем доме" vs "ты живешь в своем доме".

2023-04-30 11:27 UTC, mekarthedev commented on src/content/reference/react/useId.md
> +Чтобы создать уникальный идентификатор, вызовите `useId` на верхнем уровне своего компонента:
Если убирать, то я бы скорее наоборот здесь оставил, а дальше по тексту убрал https://github.com/reactjs/ru.react.dev/pull/856#discussion_r1181144141 – т.к. в начале вводная часть, а там дальше уже продолжение в контексте предыдущего текста

Но нужно ли?

2023-04-30 12:42 UTC, mekarthedev commented on src/content/reference/react/useId.md
> +Возможно вы задаётесь вопросом, почему лучше использовать `useId`, а не просто постоянно увеличивать некий глобальный счётчик -- наподобие `nextId++`.
Пожалуй переформулирую саму фразу. А то в моем переводе смысл заметно теряется.

2023-04-30 13:18 UTC, mekarthedev commented on src/content/reference/react/useId.md
> +`useId` -- хук для генерации уникальных идентификаторов, которые можно использовать, например, в атрибутах доступности.
Я понял, что здесь стоит делать не в стиле словарного определения, а в стиле короткого саммари как везде в оригинале. Переформулирую.

2023-05-03 09:51 UTC, mekarthedev commented on src/content/reference/react/useId.md
> +Однако в React подобным образом фиксировать идентификаторы в коде -- не лучшая практика. Один и тот же компонент может использоваться в нескольких разных местах -- но ведь в каждом случае идентификат
https://github.com/reactjs/ru.react.dev/issues/851#issuecomment-1532078179

> Разницы между ними нет, абсолютно одинаковые. Просто "—" не всегда удается вспомнить как вставить em dash, поэтому быстрее --. Используйте то, что удобнее.

2023-07-05 19:34 UTC, gcor commented on src/content/reference/react/useId.md
> +После чего вы можете указывать этот <CodeStep step={1}>сгенерированный идентификатор</CodeStep> в различных атрибутах:
чтобы не в стык было)

2023-07-05 20:24 UTC, merged

2023-07-05 20:29 UTC, mekarthedev commented on src/content/reference/react/useId.md
> +После чего вы можете указывать этот <CodeStep step={1}>сгенерированный идентификатор</CodeStep> в различных атрибутах:
Но там же не было "в стыка":

<img width="860" alt="Screenshot 2023-07-05 at 22 21 57" src="https://github.com/reactjs/ru.react.dev/assets/9768704/dd79ccb1-7c3a-474d-a39c-1d0f5c33c734">

Просто в подчеркнутом выделении появился лишний пробел:

<img width="864" alt="Screenshot 2023-07-05 at 22 22 05" src="https://github.com/reactjs/ru.react.dev/assets/9768704/eb56af69-9e4b-47fc-b4d7-b7244ae8dbd2">


Это только здесь кажется "в стык"? Или везде в проекте тоже надо этот пробел? Такое только в русском переводе, или в английском тоже нужно везде исправлять?

2023-07-05 20:43 UTC, gcor commented on src/content/reference/react/useId.md
> +После чего вы можете указывать этот <CodeStep step={1}>сгенерированный идентификатор</CodeStep> в различных атрибутах:
да, вы правы, я  ошибся.