Translation for `Strict Mode`
reactjs/ru.react.dev pull request #871
Opened 2023-05-06 13:23 UTC by jkorichneva

**Если ваш пулреквест является исправлением бага, а не переводом, то сперва убедитесь, что проблема относится ТОЛЬКО к https://ru.reactjs.org, а не к https://reactjs.org.** Если это не так, то пулреквест следует открыть в родительском репозитории.

2023-05-12 10:05 UTC, ntishkevich requested changes
Спасибо за перевод. Я оставил предложения по улучшению перевода. Также, стоит перевести текст в примерах, раз вы переводили текстовки из примеров в тексте.

2023-05-12 10:05 UTC, ntishkevich commented on src/content/reference/react/StrictMode.md
> +[Узнать больше о сбрасывающей функции в эффекте.](/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development)
```suggestion
[Узнать больше о функции сброса эффекта.](/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development)
```

2023-05-12 10:05 UTC, ntishkevich commented on src/content/reference/react/StrictMode.md
> +React предупреждает, если какой-либо компонент внутри дерева `<StrictMode>` использует какое-либо из следующих устаревших API:
```suggestion
React предупреждает, если какой-либо компонент внутри дерева `<StrictMode>` использует одно из устаревших API:
```
Перефразировал

2023-05-12 10:05 UTC, ntishkevich requested changes
Спасибо за перевод. Я оставил предложения по улучшению перевода. Также, стоит перевести текст в примерах, раз вы переводили текстовки из примеров в тексте.

2023-05-12 17:43 UTC, jkorichneva commented on src/content/reference/react/StrictMode.md
> +- Ваши компоненты будут [повторно запускать эффекты](#fixing-bugs-found-by-re-running-effects-in-development), чтобы можно было найти баги возникающие из-за отсутствия сбрасывающей функции в эффекте.
я смотрела, что там было:
| cleanup | сброс (*напр., сбрасываемый эффект, сбросить эффект, сбрасывающая функция*) |

поэтому пыталась немного заменить на синонимы)

2023-05-12 17:46 UTC, jkorichneva commented on src/content/reference/react/StrictMode.md
> +React предупреждает, если какой-либо компонент внутри дерева `<StrictMode>` использует какое-либо из следующих устаревших API:
да, так намного лучше, не заметила повтора

2023-05-12 17:51 UTC, jkorichneva commented on src/content/reference/react/StrictMode.md
> +Строгий режим может быть включён для любой части вашего приложения:
поправила, но убрала "также", потому что кажется, оно тут не нужно

2023-05-12 18:06 UTC, jkorichneva commented on src/content/reference/react/StrictMode.md
> +Без строгого режима было легко пропустить ошибку, пока вы не добавили больше ре-рендеров. Строгий режим сразу показал ошибку. Он помогает вам находить баги перед тем, как вы отправите их вашей команд
Заменила на:
которые могут испортить работу вашей команды и вызывать проблемы у ваших пользователей.

а то получается испортить работу пользователей - странно звучит

2023-05-12 18:13 UTC, jkorichneva commented on src/content/reference/react/StrictMode.md
> +* [`findDOMNode`](/reference/react-dom/findDOMNode). [Смотреть альтернативные решения.](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage)
наверное если смотрите, то тогда надо везде добавить "тут", а то как-то не очень звучит.
Я бы оставила `смотреть`наверное

2023-05-13 09:21 UTC, jkorichneva commented
> Спасибо за перевод. Я оставил предложения по улучшению перевода. Также, стоит перевести текст в примерах, раз вы переводили текстовки из примеров в тексте.

Привет, большое спасибо за комментарии и терпение!
Поправила все комменты

2023-05-18 19:49 UTC, ntishkevich reviewed
Два мелких момента, остальное выглядит отлично!

2023-05-18 19:49 UTC, ntishkevich commented on src/content/reference/react/StrictMode.md
> +Strict Mode включает дополнительные проверки для всего дерева компонентов внутри `<StrictMode>` в режиме разработки. Эти проверки позволяют находить распространенные баги в компонентах на ранней стад
Пропустил в предыдущий раз "Strict Mode", поэтому предлагаю перевести как "строгий режим" раз уже везде перевели.
```suggestion
Строгий режим включает дополнительные проверки для всего дерева компонентов внутри `<StrictMode>` в режиме разработки. Эти проверки позволяют находить распространенные баги в компонентах на ранней стадии разработки.
```

2023-05-18 19:49 UTC, ntishkevich commented on src/content/reference/react/StrictMode.md
> +Чтобы включить Strict Mode для всего приложения, оберните ваш корень вашего приложения в `<StrictMode>` при рендеринге:
Здесь аналогичная ситуация с "Strict Mode"
```suggestion
Чтобы включить строгий режим для всего приложения, оберните ваш корень вашего приложения в `<StrictMode>` при рендеринге:
```

2023-05-19 06:20 UTC, jkorichneva commented on src/content/reference/react/StrictMode.md
> +Strict Mode включает дополнительные проверки для всего дерева компонентов внутри `<StrictMode>` в режиме разработки. Эти проверки позволяют находить распространенные баги в компонентах на ранней стад
поправила

2023-05-19 06:20 UTC, jkorichneva commented on src/content/reference/react/StrictMode.md
> +Чтобы включить Strict Mode для всего приложения, оберните ваш корень вашего приложения в `<StrictMode>` при рендеринге:
и тут поправила

2023-05-19 07:06 UTC, ntishkevich approved these changes
LGTM

2023-05-20 10:40 UTC, jkorichneva commented
> LGTM

Спасибо) если что - влить я не могу, видимо, прав нет)

2023-05-21 22:21 UTC, gcor reviewed
Спасибо за перевод!

Вот несколько предложений

2023-05-21 22:21 UTC, gcor commented on src/content/reference/react/StrictMode.md
> +Используйте `StrictMode`, для активации дополнительных проверок и предупреждений для вложенного дерева компонентов:
```suggestion
Используйте `StrictMode` для активации дополнительных проверок и предупреждений для вложенного дерева компонентов:
```

2023-05-21 22:21 UTC, gcor commented on src/content/reference/react/StrictMode.md
> +[Больше примеров использования.](#usage)
```suggestion
[Больше примеров использования ниже.](#usage)
```

2023-05-21 22:21 UTC, gcor commented on src/content/reference/react/StrictMode.md
> +Строгий режим активирует следующие поведения в режиме разработки:
```suggestion
Строгий режим активирует следующие варианты поведения в режиме разработки:
```

2023-05-21 22:21 UTC, gcor commented on src/content/reference/react/StrictMode.md
> +Теперь, когда ваш эффект "сбрасывается" и удаляет устаревшие подключения, утечка устранена. Обратите внимание, что проблема не стала заметной, пока вы не добавили больше функциональности (выпадающий
```suggestion
Теперь, когда ваш эффект "убирает" за собой устаревшие подключения, утечка устранена. Обратите внимание, что проблема не стала заметной, пока вы не добавили больше функциональности (выпадающий список).
```

2023-05-23 17:37 UTC, jkorichneva commented
> Вот несколько предложений

@gcor Привет, обновила, сорри за задержку

2023-07-05 19:16 UTC, merged