Translation for "Sharing State Between Components"
reactjs/ru.react.dev pull request #872
Opened 2023-05-06 22:41 UTC by arturdedela

**Если ваш пулреквест является исправлением бага, а не переводом, то сперва убедитесь, что проблема относится ТОЛЬКО к https://ru.reactjs.org, а не к https://reactjs.org.** Если это не так, то пулреквест следует открыть в родительском репозитории.

2023-05-06 22:44 UTC, arturdedela commented on src/content/learn/sharing-state-between-components.md
>  <YouWillLearn>
YouWillLearn, где-то отдельно будет переведен, правильно понимаю?
![Screenshot 2023-05-06 at 18 42 57](https://user-images.githubusercontent.com/15185407/236649273-751e43b1-a267-4f5a-a810-ac3f317c75cc.jpeg)

2023-05-21 23:12 UTC, gcor reviewed
Спасибо вам большое!

Вот несколько предложений

2023-05-21 23:12 UTC, gcor commented on src/content/learn/sharing-state-between-components.md
пожалуйста удалить лишний перенос строку, чтобы в будущем не было проблем при ребейзе.

2023-05-21 23:12 UTC, gcor commented on src/content/learn/sharing-state-between-components.md
> +Теперь родитель компонента `Panel`  может *управлять* `isActive` [передавая его вниз как проп.](/learn/passing-props-to-a-component) С другой стороны, компонент `Panel` теперь *не имеет контроля* над
```suggestion
Теперь родитель компонента `Panel` может *управлять* `isActive`, [передавая его вниз как проп.](/learn/passing-props-to-a-component) С другой стороны, компонент `Panel` теперь *не имеет контроля* над значением `isActive`--теперь оно зависит от родительского компонента!
```

2023-05-21 23:12 UTC, gcor commented on src/content/learn/sharing-state-between-components.md
> +На практике, "управляемые" и "неуправляемые" это не строгие технические определения--обычно компоненты имеют и внутреннее состояние и пропсы. Однако, важно понимать как устроены компоненты и какие во
```suggestion
На практике «управляемые» и «неуправляемые» это не строгие технические определения--обычно компоненты имеют и внутреннее состояние и пропсы. Однако, важно понимать как устроены компоненты и какие возможности они предоставляют.
```

2023-05-21 23:12 UTC, gcor commented on src/content/learn/sharing-state-between-components.md
> +В приложении на React у многих компонентов будет свое собственное состояние. Какое-то состояние может "жить" близко к листовым компонентам (компоненты внизу дерева), например, текстовое поле. Другое
```suggestion
В приложении на React у многих компонентов будет свое собственное состояние. Какое-то состояние может «жить» близко к листовым компонентам (компоненты внизу дерева), например, текстовое поле. Другое состояние может «жить» ближе к корню приложения. Например, даже при реализации библиотеки клиентской маршрутизации, текущий путь обычно сохраняют в состояние React и передают его вниз через пропсы.
```

пожалуйста поменяйте тут и в других местах кавычки на «ёлочки»

2023-05-21 23:12 UTC, gcor commented on src/content/learn/sharing-state-between-components.md
> +**Для каждого уникального кусочка состояния, вы будете выбирать, какой компонент будет им "владеть".** Этот принцип также известен как наличие ["единого источника истины".](https://en.wikipedia.org/w
```suggestion
**Для каждого уникального кусочка состояния вы выбираете компонент, который «владеет» им** Этот принцип также известен как наличие ["единого источника истины".](https://en.wikipedia.org/wiki/Single_source_of_truth) Это не означает, что все состояние React находится в одном месте--для _каждой_ части состояния существует _конкретный_ компонент, который хранит эту информацию. 
```

  
Пожалуйста, проверьте запятые. Есть разница в правилах с английским языком.

2023-05-21 23:12 UTC, gcor commented on src/content/learn/sharing-state-between-components.md
> +Вместо дублирования общего состояния между компонентами, *поднимите* его в общий родительский компонент и "пробросьте" его дочерним компонентам, которым он необходим.
Пожалуйста удалите перенос. Для корректного ребейза в будущем нужно чтобы строчки совпадали

2023-05-21 23:12 UTC, gcor commented on src/content/learn/sharing-state-between-components.md
> +Вместо дублирования общего состояния между компонентами, *поднимите* его в общий родительский компонент и "пробросьте" его дочерним компонентам, которым он необходим.
```suggestion
Вместо дублирования общего состояния между компонентами, *поднимите* его в общий родительский компонент и «пробросьте» его дочерним компонентам, которым он необходим.
```

2023-05-21 23:12 UTC, gcor commented on src/content/learn/sharing-state-between-components.md
> +Ваше приложение будет меняться по мере работы над ним. Это нормально, что вы будете перемещать состояние вниз или обратно вверх, пока разбираетесь где "живет" каждая часть состояния. Это все часть пр
```suggestion
Ваше приложение будет меняться по мере работы над ним. Это нормально, что вы будете перемещать состояние вниз или обратно вверх, пока разбираетесь где «живет» каждая часть состояния. Это все часть процесса!
```

2023-05-21 23:12 UTC, gcor commented on src/content/learn/sharing-state-between-components.md
> +Чтобы увидеть, как это работает на практике с другими компонентами, прочитайте статью [Мышление в React.](/learn/thinking-in-react).
```suggestion
Чтобы увидеть как это работает на практике с другими компонентами, прочитайте статью [Мыслим на React.](/learn/thinking-in-react).
```

2023-05-21 23:13 UTC, gcor commented on src/content/learn/sharing-state-between-components.md
> +Чтобы увидеть, как это работает на практике с другими компонентами, прочитайте статью [Мышление в React.](/learn/thinking-in-react).
Финальный заголовок этой страницы будет тут:
https://github.com/reactjs/ru.react.dev/pull/876

2023-07-05 20:45 UTC, gcor commented on src/content/learn/sharing-state-between-components.md
>  <YouWillLearn>
если есть возможность, можете поправить?

2023-07-20 17:39 UTC, titovmx requested changes
Спасибо за перевод! Оставил несколько замечаний и предложений. Надеюсь, вы на связи и сможете добить этот PR!

2023-07-20 17:39 UTC, titovmx commented on src/content/learn/sharing-state-between-components.md
> +В нашем случае, только одна панель должна быть активна одновременно. Это означает, что общему родителю `Accordion` нужно следить за тем *какая* панель активна в данный момент. Вместо булевого значени
```suggestion
В нашем случае только одна панель должна быть активна одновременно. Это означает, что общему родителю `Accordion` нужно следить за тем *какая* панель активна в данный момент. Вместо булевого значения в состоянии можно хранить число, которое будет означать индекс активной панели:
```
Здесь также не требуется обособление

2023-07-20 17:39 UTC, titovmx commented on src/content/learn/sharing-state-between-components.md
> +Нажатие на кнопку «Показать» в любой из панелей должно изменять индекс активной панели в `Accordion`. `Panel` не может напрямую установить состояние `activeIndex`, потому что оно определено внутри `A
```suggestion
Нажатие на кнопку «Показать» в любой из панелей должно изменять индекс активной панели в `Accordion`. `Panel` не может напрямую установить состояние `activeIndex`, потому что оно определено внутри `Accordion`. Компонент `Accordion` должен *явно разрешить* компоненту `Panel` изменять свое состояние, [передав обработчик события как проп](/learn/responding-to-events#passing-event-handlers-as-props):
```
мне кажется, так попроще звучит

2023-07-20 17:39 UTC, titovmx commented on src/content/learn/sharing-state-between-components.md
> +В начале, `activeIndex` в компоненте `Accordion` имеет значение 0, поэтому первая панель получает `isActive = true`
```suggestion
Сначала `activeIndex` в компоненте `Accordion` имеет значение 0, поэтому первая панель получает `isActive = true`
```

2023-07-20 17:39 UTC, titovmx commented on src/content/learn/sharing-state-between-components.md
> +На практике «управляемые» и «неуправляемые» это не строгие технические определения--обычно компоненты имеют и внутреннее состояние и пропсы. Однако, важно понимать как устроены компоненты и какие воз
```suggestion
На практике «управляемые» и «неуправляемые» это не строгие технические определения--обычно компоненты имеют и внутреннее состояние, и пропсы. Однако, важно понимать как устроены компоненты и какие возможности они предоставляют.
```

2023-07-20 17:39 UTC, titovmx commented on src/content/learn/sharing-state-between-components.md
> +* Полезно рассматривать компоненты как «управляемые» (управляемые пропами) или «неуправляемые» (управляемые состоянием).
```suggestion
* Полезно рассматривать компоненты как «управляемые» (управляемые пропсами) или «неуправляемые» (управляемые состоянием).
```
По соглашению пишем "пропсами"

2023-07-20 17:39 UTC, titovmx commented on src/content/learn/sharing-state-between-components.md
> +Напротив, компонент называют «управляемым», если важная информация зависит от пропов, а не от внутреннего состояния. Это позволяет родительскому компоненту полностью контролировать его поведение. Пос
```suggestion
Напротив, компонент называют «управляемым», если важная информация зависит от пропсов, а не от внутреннего состояния. Это позволяет родительскому компоненту полностью контролировать его поведение. После наших изменений, компонентом `Panel` управляет компонент `Accordion` с помощью пропа `isActive`.
```
по соглашению во множественном числе будет "пропсов"

2023-07-20 17:39 UTC, titovmx commented on src/content/learn/sharing-state-between-components.md
>          onChange={handleChange}
Вы могли бы перевести этот пример (массив `foods` в частности) полностью?

2025-02-21 13:20 UTC, closed without merging