Translation for Hooks / useRef
reactjs/ru.react.dev pull request #885
Opened 2023-05-17 06:27 UTC by jewhyena

This PR translates the  API Reference / Hooks / useRef article.

2023-07-24 15:03 UTC, titovmx commented
@jewhyena обратите, пожалуйста, внимание на конфликт с мастером

2023-07-24 15:35 UTC, titovmx requested changes
привет! спасибо за перевод! всего пара комментариев

2023-07-24 15:35 UTC, titovmx commented on src/content/reference/react/useRef.md
> +* При изменении свойства `ref.current` React не ререндерит компонент. Поскольку реф это простой JavaScript-объект, React ничего не знает о его изменениях.
```suggestion
* При изменении свойства `ref.current` React не рендерит компонент повторно. Поскольку реф это простой JavaScript-объект, React ничего не знает о его изменениях.
```
по [соглашению](https://github.com/reactjs/ru.react.dev/blob/main/TRANSLATION.md#%D1%81%D0%BE%D0%B3%D0%BB%D0%B0%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D0%BE-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4%D1%83-%D0%B3%D0%BB%D0%BE%D1%81%D1%81%D0%B0%D1%80%D0%B8%D0%B9) не используем "ререндер". Здесь по контексту, на мой взгляд, достаточно будет "не рендерит", "не вызывает рендер компонента" или можно добавить "повторно". Также, пожалуйста, проверьте другие использования "ререндер" по переводу.

2023-07-24 15:35 UTC, titovmx commented on src/content/reference/react/useRef.md
> +Если вы используете тайп-чекер и не хотите постоянно проверять значение на `null`, можно воспользоваться следующим паттерном:
```suggestion
Если в вашем проекте есть проверка типов и вы не хотите постоянно проверять значение на `null`, можно воспользоваться следующим паттерном:
```
может попробовать избежать "тайп-чекер"? ничего устоявшегося я не нашел, так что предлагаю немного перефразировать - что думаете?

2025-01-07 21:21 UTC, jewhyena commented
@titovmx, @gcor, привет! есть у кого возможность пересмотреть и смёрджить?

лишь недавно появилось время вернуться и исправить тут конфликты – теперь всё в порядке должно быть, поэтому, думаю, было бы неплохо покончить с этим пулреквестом, а то уж полтора года висит

2025-01-08 04:38 UTC, titovmx approved these changes

2025-01-08 04:39 UTC, merged