Translation for Updating Objects in State page
reactjs/ru.react.dev pull request #886
Opened 2023-05-17 20:55 UTC by bofeof

**Если ваш пулреквест является исправлением бага, а не переводом, то сперва убедитесь, что проблема относится ТОЛЬКО к https://ru.reactjs.org, а не к https://reactjs.org.** Если это не так, то пулреквест следует открыть в родительском репозитории.

2023-07-27 15:36 UTC, titovmx requested changes
Привет! Спасибо за перевод! Оставил несколько комментариев и предложений

2023-07-27 15:36 UTC, titovmx commented on src/content/learn/updating-objects-in-state.md
> +## Копирование объектов с использованием спред-синтаксиса {/*copying-objects-with-the-spread-syntax*/}
```suggestion
## Копирование объектов с использованием оператора расширения {/*copying-objects-with-the-spread-syntax*/}
```
Здесь и ниже в переводе я бы рекомендовал использовать [оператор расширения ](https://learn.javascript.ru/rest-parameters-spread-operator). Или синтаксис расширения.

2023-07-27 15:36 UTC, titovmx commented on src/content/learn/updating-objects-in-state.md
> +В предыдущем примере, объект `position` всегда создаётся заново, исходя из текущей позиции курсора. На практике чаще всего вы захотите включать уже *существующие* данные в новый объект, который вы со
```suggestion
В предыдущем примере объект `position` всегда создаётся заново, исходя из текущей позиции курсора. На практике чаще всего вы захотите включать уже *существующие* данные в новый объект, который вы создаёте. Например, вы можете захотеть обновить *только одно* поле в форме, остальные значения полей сохранить без изменений.
```
В русском не обособляется

2023-07-27 15:36 UTC, titovmx commented on src/content/learn/updating-objects-in-state.md
Вы могли бы перевести примеры и в этом переводе?

2023-07-27 15:36 UTC, titovmx commented on src/content/learn/updating-objects-in-state.md
> +Вы можете использовать `...` [спред-оператор,](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals) чтобы вам не нужно было копировать
```suggestion
Вы можете использовать `...` [оператор расширения,](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_%D0%B2_%D0%BB%D0%B8%D1%82%D0%B5%D1%80%D0%B0%D0%BB%D0%B0%D1%85_%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%B0) чтобы вам не нужно было копировать каждое свойство отдельно.
```
Обновил ссылку на русскоязычный вариант статьи в mdn.

2023-07-27 15:36 UTC, titovmx commented on src/content/learn/updating-objects-in-state.md
> +Если ваш объект имеет несколько уровней вложенности, вы можете подумать об [упрощении структуры объекта.](/learn/choosing-the-state-structure#avoid-deeply-nested-state) Однако, если вы не хотите изме
```suggestion
Если ваш объект имеет несколько уровней вложенности, вы можете подумать об [упрощении структуры объекта.](/learn/choosing-the-state-structure#avoid-deeply-nested-state) Однако, если вы не хотите изменять структуру объекта, вы можете ссылаться на вложенные объекты. [Immer](https://github.com/immerjs/use-immer) -- это популярная библиотека, которая позволяет вам использовать удобный, но мутирующий синтаксис. Кроме того, она ответственна за создание копий объекта. С Immer ваш код выглядит так, будто вы "нарушили правило" и мутировали объект:
```
может уже лучше разбить на два предложения?

2023-07-27 15:36 UTC, titovmx commented on src/content/learn/updating-objects-in-state.md
> +`draft`, предоставленный Immer, является особенным типом объекта, который называется [прокси](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), он "записывает"
```suggestion
`Черновик`, предоставленный Immer, является особенным типом объекта, который называется [прокси](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), он "записывает" то, что вы с ним делаете. Вот почему вы можете мутировать его столько раз, сколько захотите! Под капотом Immer выясняет, какие части `черновика` были изменены, и создаёт новый объект с наличием этих изменений.
```
На мой взгляд, здесь можно перевести. По поиску "Immer черновик" находятся статьи на хабре и хекслете

2023-07-27 15:36 UTC, titovmx commented on src/content/learn/updating-objects-in-state.md
> +* Вместо этого, создайте *новую* версию объекта и активируйте повторный рендер, установив для него состояние.
```suggestion
* Вместо этого создайте *новую* версию объекта и активируйте повторный рендер, установив для него состояние.
```
Кажется, тут тоже не нужно обособление

2023-07-27 16:25 UTC, bofeof commented on src/content/learn/updating-objects-in-state.md
> +До сих пор вы работали с числами, строками и логическими значениями. Эти виды значений в JavaScript являются "иммутабельными" -- это значит, что они не изменяются и доступны "только для чтения". Вы м
а если так поступить: "являются иммутабельными (далее — неизменяемыми)"
и просто работать с "неизменяемый" дальше по тексту, мы так два варианта определения покажем сразу

2023-07-28 06:17 UTC, titovmx commented on src/content/learn/updating-objects-in-state.md
> +До сих пор вы работали с числами, строками и логическими значениями. Эти виды значений в JavaScript являются "иммутабельными" -- это значит, что они не изменяются и доступны "только для чтения". Вы м
мне кажется, это хороший подход

2023-08-08 14:36 UTC, titovmx commented on src/content/learn/updating-objects-in-state.md
> +До сих пор вы работали с числами, строками и логическими значениями. Эти виды значений в JavaScript являются "иммутабельными" -- это значит, что они не изменяются и доступны "только для чтения". Вы м
новая вводная по поводу этого комментария - в соглашении этого репозитория всё же есть договорённость переводить "immutable" как "иммутабельный". Я просмотрел, потому что они приведены чуть ниже на букву m. Так что извините меня за переполох, давайте придерживаться этого варианта по всему тексту. Хорошо, если еще не правили :)
Впрочем, по-прежнему можно добавить "неизменяемый" в скобках при первом использовании. На ваше усмотрение.

2023-08-08 14:38 UTC, bofeof commented on src/content/learn/updating-objects-in-state.md
> +До сих пор вы работали с числами, строками и логическими значениями. Эти виды значений в JavaScript являются "иммутабельными" -- это значит, что они не изменяются и доступны "только для чтения". Вы м
спасибо за информацию! все в порядке, в ближайшее время отправлю новый вариант работы :)

2023-10-19 09:23 UTC, bofeof commented
@titovmx привет! исправила, перевод готов для ревью :)

2023-10-22 09:05 UTC, titovmx approved these changes
Спасибо за обновление! Заметил только ещё одну ссылку, для которой есть перевод.
Считаю, что получилась отличная статья!

2023-10-22 09:21 UTC, bofeof commented
@titovmx Максим, спасибо за совместную работу!

2025-05-12 17:37 UTC, dimatitov commented
Привет! 👋
Кажется, все замечания были учтены.
@titovmx, посмотри, пожалуйста, если всё ок, может, уже можно мержить?

2025-06-14 16:50 UTC, bofeof commented
@titovmx @dimatitov привет!
ребят, и правда, а когда будет мердж? перевод достаточно настоялся :D

2025-06-14 18:34 UTC, titovmx commented
ух ты, я просмотрел. Спасибо за напоминание!

2025-06-14 18:34 UTC, merged

2025-06-14 22:45 UTC, dimatitov commented
@bofeof Спасибо за перевод)