Translate memo
reactjs/ru.react.dev pull request #923
Opened 2023-11-06 15:40 UTC by maridoroshuk

2023-11-14 15:28 UTC, titovmx requested changes
Спасибо за перевод! Оставил несколько комментариев и предложений.
Пожалуйста, проверьте использование буквы Ё по всему переводу.

2023-11-14 15:28 UTC, titovmx commented on src/content/reference/react/memo.md
> +1. Избегайте [ненужных Эффектов, которые обновляют состояние](/learn/you-might-not-need-an-effect). Большинство проблем с производительностью в React приложении вызвано цепочкой обновлений в  `useEff
```suggestion
1. Избегайте [ненужных Эффектов, которые обновляют состояние](/learn/you-might-not-need-an-effect). Большинство проблем с производительностью в React-приложении вызвано цепочкой обновлений в `useEffect`, которые заставляют ваши компоненты рендериться снова и снова.
```

2023-11-14 15:28 UTC, titovmx commented on src/content/reference/react/memo.md
> +Если какое-то конкретное действие все еще происходит с задержкой,  [используйте React Developer Tools profiler,](https://legacy.reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html) чтобы
```suggestion
Если какое-то конкретное действие все еще происходит с задержкой,  [используйте профилировщик React Developer Tools,](https://legacy.reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html) чтобы понять для каких компонентов мемоизация будет наиболее подходящей и добавьте ее, где требуется. Этот принцип позволяет легко понимать и производить отладку ваших компонентов. В долгосрочной перспективе мы исследуем возможность [детальной мемоизации автоматически](https://www.youtube.com/watch?v=lGEMwh32soc), чтобы решить это раз и навсегда. 
```

2023-11-14 15:28 UTC, titovmx commented on src/content/reference/react/memo.md
> +Если вам нужно передать функцию в мемоизированный компонент, либо определите ее вне вашего компонента, в таком случае она никогда не изменится,  либо используйте [`useCallback,`](/reference/react/use
```suggestion
Если вам нужно передать функцию в мемоизированный компонент, либо определите ее вне вашего компонента, в таком случае она никогда не изменится, либо используйте [`useCallback,`](/reference/react/useCallback#skipping-re-rendering-of-components) чтобы сохранить определение вашей функции между повторными рендерами.
```
снова лишний пробел 🤔

2023-11-14 15:28 UTC, titovmx commented on src/content/reference/react/memo.md
> +React поверхностно сравнивает старые и новые пропсы: это значит, что проверяется ссылка старого и нового пропа. Если вы создаете новый объект или массив, родительский компонент рендерится повторно, д
```suggestion
React поверхностно сравнивает старые и новые пропсы: это значит, что проверяется ссылка старого и нового пропа. Если вы создаете новый объект или массив, родительский компонент рендерится повторно, даже если конкретный элемент каждый раз такой же, React по-прежнему будет считать, что он изменился. То же самое происходит, когда вы создаете функцию, при рендере родительского компонента, React будет считать, что она изменилась даже, если определение функции осталось прежним. Чтобы избежать такого поведения, [делайте пропсы проще или мемоизируйте пропсы родительского компонента](#minimizing-props-changes).
```

2023-11-23 10:26 UTC, maridoroshuk commented
@titovmx  большое спасибо за ревью!

2024-06-29 11:18 UTC, titovmx approved these changes

2024-06-29 11:18 UTC, merged