Translation for Understanding Your UI as a Tree
reactjs/ru.react.dev pull request #927
Opened 2023-11-27 17:57 UTC by L1ghT0

**Если ваш пулреквест является исправлением бага, а не переводом, то сперва убедитесь, что проблема относится ТОЛЬКО к https://ru.reactjs.org, а не к https://reactjs.org.** Если это не так, то пулреквест следует открыть в родительском репозитории.

2024-03-13 07:29 UTC, titovmx requested changes
Спасибо за перевод! Извините, что долго не получалось посмотреть.
Оставил несколько комментариев, некоторые повторяющиеся - их стоит перепроверить по всему переводу.
Также, пожалуйста, обратите внимание на конфликты в ветке.

2024-03-13 07:29 UTC, titovmx commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +Дерево — это модель отношений между элементами и UI часто использует эту структуру. Например, браузеры используют тот же подход для построения HTML ([DOM](https://developer.mozilla.org/docs/Web/API/D
```suggestion
Дерево — это модель отношений между элементами, и UI часто использует эту структуру. Например, браузеры используют тот же подход для построения HTML ([DOM](https://developer.mozilla.org/docs/Web/API/Document_Object_Model/Introduction)) и CSS ([CSSOM](https://developer.mozilla.org/docs/Web/API/CSS_Object_Model)). Мобильные платформы так же используют структуру дерева для своей иерархии.
```
Сложносочинённое предложение, нужна запятая между двух частей

2024-03-13 07:29 UTC, titovmx commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +React создает UI дерево из ваших компонентов. В этом случае дерево UI используется для последующего рендеринга в DOM.
```suggestion
React создаёт UI-дерево из ваших компонентов. В этом случае дерево UI используется для последующего рендеринга в DOM.
```
1. Пожалуйста, проверьте, что везде использована буква "ё". В этом вам поможет библиотека [eyo](https://www.npmjs.com/package/eyo).
2. Англоязычные термины в связке с другим существительным образуют сложные существительные и требуют использования дефиса. Пожалуйста, перепроверьте подобные случаи по всему переводу.

2024-03-13 07:29 UTC, titovmx commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +React, так же как браузеры и мобильные платформы, использует структуру дерева для управления и построения связи между компонентами. Эти деревья являются полезным инструментом и помогут вам понять как
```suggestion
React, так же как браузеры и мобильные платформы, использует структуру дерева для управления и построения связи между компонентами. Эти деревья являются полезным инструментом и помогут вам понять как данные проходят через приложение React, как оптимизировать рендеринг и размер приложения.
```
может через запятую?

2024-03-13 07:29 UTC, titovmx commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +Когда мы рендерим React приложение, мы можем смоделировать эти связи в виде дерева, известного как дерево рендеринга.
```suggestion
Когда мы рендерим React-приложение, мы можем смоделировать эти связи в виде дерева, известного как дерево рендеринга.
```

2024-03-13 07:29 UTC, titovmx commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +Вот пример приложения React, которое отображает вдохновляющие цитаты.
могли бы ваше также перевести текст в примерах, который отображается пользователям?

2024-03-13 07:29 UTC, titovmx commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +React создает *дерево рендеринга* и UI дерево состоящих из компонентов прошедших рендеринг.
```suggestion
React создает *дерево рендеринга* и UI-дерево, состоящее из компонентов, прошедших рендеринг.
```
тут два причастных оборота, можно было бы подумать как упростить

2024-03-13 07:29 UTC, titovmx commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +Корневой узел в дереве рендеринга React является [корневым компонентом](/learn/importing-and-exporting-components#the-root-component-file) приложения. В нашем случае корневой компонент предстовляет `
```suggestion
Корневой узел в дереве рендеринга React является [корневым компонентом](/learn/importing-and-exporting-components#the-root-component-file) приложения. В нашем случае корневой компонент предстовлен `App`, и React рендерит его первым. Каждое ответление в дереве идёт от родительского компонента к дочернему.
```
Сложносочинённое предложение

2024-03-13 07:29 UTC, titovmx commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +Как фреймворк UI, React является платформо-независимым. Здесь же мы демонстрируем примеры рендеринга в web, где в качестве примитивов UI используется разметка HTML. Но приложение React так же может з
```suggestion
Как UI-фреймворк, React является платформонезависимым. В документации мы демонстрируем примеры рендеринга в web, где в качестве примитивов UI используется разметка HTML. Но приложение React так же может запускаться на мобильных или десктоп платформах, которые используют другие UI-примитивы, такие как: [UIView](https://developer.apple.com/documentation/uikit/uiview) или [FrameworkElement](https://learn.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement?view=windowsdesktop-7.0).
```
Мне показалось не очень очевидно где это "здесь же" 😃

2024-03-13 07:29 UTC, titovmx commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +Но примитивы на этих платформах не являются частью React и его дерево так же может давать представление о нашем приложении независимо от того, на какой платформе запускается ваше приложение.
```suggestion
Но примитивы на этих платформах не являются частью React. Его дерево может давать представление о вашем приложении независимо от того, на какой платформе запускается ваше приложение.
```
Предлагаю разбить на два приложения тут для простоты

2024-03-13 07:29 UTC, titovmx commented on src/content/learn/understanding-your-ui-as-a-tree.md
>  <Diagram name="module_dependency_tree" height={250} width={658} alt="A tree graph with seven nodes. Each node is labelled with a module name. The top level node of the tree is labelled 'App.js'. Ther
Переведите, пожалуйста, текст в `alt` - это нужно для доступности приложения. Здесь и для других диаграмм.

2024-03-13 07:29 UTC, titovmx commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +По мере роста вашего приложения часто увеличивается и размер сборщика. При больших размерах требуются больше затрат для загрузки и запуска клиента, а так же это может задерживать прорисовку вашего UI
```suggestion
По мере роста вашего приложения часто увеличивается и размер сборщика. При больших размерах требуется больше затрат для загрузки и запуска клиента, а так же это может задерживать прорисовку вашего UI. Понимание же дерева зависимостей вашего приложения может помочь в отладке и устранении этих проблем.
```

2024-03-13 07:29 UTC, titovmx commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +* Деревья — это распространенный способ показать отношение между сущностями. Они очень частно используются для построения UI.
```suggestion
* Деревья — это распространенный способ показать отношения между сущностями. Они очень частно используются для построения UI.
```

2024-03-21 04:50 UTC, L1ghT0 commented on src/content/learn/understanding-your-ui-as-a-tree.md
> +Вот пример приложения React, которое отображает вдохновляющие цитаты.
Commit:  70b8c837d3e5c946902ab8ea0bec0ea02f6f8ec3

2024-03-21 05:03 UTC, L1ghT0 commented
> Спасибо за перевод! Извините, что долго не получалось посмотреть. Оставил несколько комментариев, некоторые повторяющиеся - их стоит перепроверить по всему переводу. Также, пожалуйста, обратите внимание на конфликты в ветке.

Извиняюсь за задержку. Вроде все сделал. Есть небольшие сомнения в переводе цитат в этом коммите: (70b8c837d3e5c946902ab8ea0bec0ea02f6f8ec3).

2024-04-29 18:09 UTC, merged