Обновить tutorial-tic-tac-toe.md
reactjs/ru.react.dev pull request #952
Opened 2024-05-10 08:58 UTC by SmaylikYoutuber

**Если ваш пулреквест является исправлением бага, а не переводом, то сперва убедитесь, что проблема относится ТОЛЬКО к https://ru.reactjs.org, а не к https://reactjs.org.** Если это не так, то пулреквест следует открыть в родительском репозитории.

2024-05-10 13:35 UTC, titovmx requested changes
Спасибо за перевод! Оставил несколько комментариев

2024-05-10 13:35 UTC, titovmx commented on src/content/learn/tutorial-tic-tac-toe.md
> +- [Обзор](#overview) научит вас **основам** React: компонентам, реквизитам и состоянию.
```suggestion
- [Обзор](#overview) познакомит вас с **основами** React: компонентами, пропсами и состоянием.
```
props переводим как пропсы, по договорённости.
так же предлагаю немного переформулировать.

2024-05-10 13:35 UTC, titovmx commented on src/content/learn/tutorial-tic-tac-toe.md
> +- [Завершение игры научит](#completing-the-game) вас **наиболее распространенным методам** в разработке React.
```suggestion
- [Завершение игры научит](#completing-the-game) вас **наиболее распространённым методам** в разработке React.
```
проверьте, пожалуйста, что в переводе используется буква ё. для этого можно использовать библиотеку [eyo](https://www.npmjs.com/package/eyo)

2024-05-10 13:35 UTC, titovmx commented on src/content/learn/tutorial-tic-tac-toe.md
> +- [Добавление путешествие во времени](#adding-time-travel) даст вам **более глубокое представление** об уникальных сильных сторонах React.
```suggestion
- [Добавление путешествия во времени](#adding-time-travel) даст вам **более глубокое представление** об уникальных сильных сторонах React.
```
так правильнее согласовать будет? может заменить "путешествие" на "перемещение"?

2024-05-10 13:35 UTC, titovmx commented on src/content/learn/tutorial-tic-tac-toe.md
> +В этом уроке вы создадите интерактивную игру в tic-tac-toe с React.
```suggestion
В этом уроке вы создадите интерактивную игру в крестики-нолики с React.
```
давайте везде переводить

2024-05-10 13:35 UTC, titovmx commented on src/content/learn/tutorial-tic-tac-toe.md
> +Вы можете увидеть, как это будет выглядеть, когда вы закончите здесь:
```suggestion
Вы можете увидеть ожидаемый результат здесь:
```
предлагаю упростить

2024-05-10 13:35 UTC, titovmx commented on src/content/learn/tutorial-tic-tac-toe.md
> +    status = 'Выйграл: ' + winner;
```suggestion
    status = 'Победитель: ' + winner;
```

2024-05-10 13:35 UTC, titovmx commented on src/content/learn/tutorial-tic-tac-toe.md
> +      description = 'Перейти к перемещению #' + move;
```suggestion
      description = 'Перейти к ходу #' + move;
```
думаю, тут подразумевается ход игрока

2024-05-10 13:35 UTC, titovmx commented on src/content/learn/tutorial-tic-tac-toe.md
> +      description = 'Перейти к перемещению #' + move;
и согласуется с переводом ниже

2024-05-10 13:35 UTC, titovmx commented on src/content/learn/tutorial-tic-tac-toe.md
> +После того, как вы поиграете с готовой игрой в крестики-нолики, продолжайте прокручивать. В этом руководстве вы начнете с более простого шаблона. Наш следующий шаг - настроить вас так, чтобы вы могли
```suggestion
После того, как вы поиграете с готовой игрой в крестики-нолики, продолжайте чтение. В этом руководстве вы начнете с более простого шаблона. Наш следующий шаг - настроить вас так, чтобы вы могли приступить к созданию игры.
```
может так?

2024-05-10 13:35 UTC, titovmx commented on src/content/learn/tutorial-tic-tac-toe.md
>  1. Install the dependencies with `npm install`
две строчки остались не переведены

2024-05-10 13:35 UTC, titovmx commented on src/content/learn/tutorial-tic-tac-toe.md
> +1. Скачайте [Node.js](https://nodejs.org/en/)
надо согласовать вводное предложение и пункты.
сейчас получается "Для этого вам необходимо скачайте Node.js"

2024-05-11 06:29 UTC, SmaylikYoutuber commented on src/content/learn/tutorial-tic-tac-toe.md
> +После того, как вы поиграете с готовой игрой в крестики-нолики, продолжайте прокручивать. В этом руководстве вы начнете с более простого шаблона. Наш следующий шаг - настроить вас так, чтобы вы могли
да так лучше

2024-05-11 06:29 UTC, SmaylikYoutuber commented on src/content/learn/tutorial-tic-tac-toe.md
>  1. Install the dependencies with `npm install`
я не успел

2024-05-11 07:46 UTC, SmaylikYoutuber commented
А как еще переводить просто опять как заново делал?

2024-05-12 07:42 UTC, SmaylikYoutuber commented on src/content/learn/tutorial-tic-tac-toe.md
> +Вторая строка возвращает значение button. Ключевое слово JavaScript `return/возвращает` означает, что все, что следует за ним, возвращается в качестве значения вызывающей функции. "<button>` - это эл
Прости тут ошибка Вторая строка возвращает значение button. Ключевое слово JavaScript `return/возвращает` означает, что все, что следует за ним, возвращается в качестве значения вызывающей функции. "<button>"

2024-05-20 16:09 UTC, titovmx commented
@SmaylikYoutuber привет! Обычно процесс такой:
1. Вы выбираете статью для перевода и резервируете её за собой [здесь](https://github.com/reactjs/ru.react.dev/issues/843). Также там ссылка на правила перевода, если ещё не видели, то, пожалуйста, ознакомьтесь с ними.
2. Создаёте ветку в форкнутом репозитории, переводите и создаёте пулл реквест.
3. Кто-то ревьюит, оставляет комменты, вы фиксите в этом же пулл реквесте.
4. Аппрув, мерж, и переведённая статья попадает на сайт.

Если я правильно понял, сейчас вы правки внесли в новой ветке, но перевод ещё не закончен? Если так, то давайте закроем этот ПР и продолжим перевод там. Пока перевод не закончен, вы можете пометить пулл реквест как Черновик (Draft), чтобы статус был прозрачен для тех, кто будет проводить ревью.

2024-06-13 19:05 UTC, SmaylikYoutuber commented
@titovmx а можно по подробнее я сильно не разбираюсь в GitHub, я тут как новичок пришел просто помочь перевести, может какое-то видео подскажешь как продолжить перевод, а то я вообще не понял что было в верхней строчке. (Извини что не до конца понял и прошу написать по подробнее, что из за это-го я мучаю тебя, если ответишь буду рад)

2024-06-13 19:08 UTC, SmaylikYoutuber commented
вот может ссылку кинуть на новый перевод https://github.com/reactjs/ru.react.dev/pull/953

2024-06-16 10:48 UTC, closed without merging