Add Russian translation for synchronizing-with-effects page
reactjs/ru.react.dev pull request #988
Opened 2024-11-25 10:39 UTC by Tata-Sysueva

2025-01-21 19:08 UTC, titovmx requested changes
Спасибо, отличный перевод!
Предложил обновлённые ссылки на русскоязычные статьи mdn и ещё несколько повторяющихся комментариев.

2025-01-21 19:08 UTC, titovmx commented on src/content/learn/synchronizing-with-effects.md
> +В дополнение к игнорированию результата устаревшего API-запроса, вы также можете использовать [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) для отмены запросов
```suggestion
В дополнение к игнорированию результата устаревшего API-запроса, вы также можете использовать [`AbortController`](https://developer.mozilla.org/ru/docs/Web/API/AbortController) для отмены запросов, которые больше не нужны. Однако этого недостаточно, чтобы защититься от состояний гонки. После получения данных могут быть связаны дополнительные асинхронные шаги, поэтому использование явного флага, такого как `ignore`, является самым надежным способом решения этой проблемы.
```

2025-01-21 19:08 UTC, titovmx commented on src/content/learn/synchronizing-with-effects.md
> +Вот почему вы видите биографию Боба, даже когда выбрана Тейлор. Ошибки такого рода называются [гонки состояний](https://en.wikipedia.org/wiki/Race_condition), потому что две асинхронные операции "сор
```suggestion
Вот почему вы видите биографию Боба, даже когда выбрана Тейлор. Ошибки такого рода называются [гонки состояний](https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5_%D0%B3%D0%BE%D0%BD%D0%BA%D0%B8), потому что две асинхронные операции "соревнуются" друг с другом, и они могут завершиться в неожиданном порядке.
```

2025-01-21 19:08 UTC, titovmx commented on src/content/learn/synchronizing-with-effects.md
> +Чтобы исправить этот код, сохраните идентификатор интервала, возвращаемый `setInterval`, и реализуйте функцию очистки с помощью [`clearInterval`](https://developer.mozilla.org/en-US/docs/Web/API/clea
```suggestion
Чтобы исправить этот код, сохраните идентификатор интервала, возвращаемый `setInterval`, и реализуйте функцию очистки с помощью [`clearInterval`](https://developer.mozilla.org/ru/docs/Web/API/clearInterval):
```

2025-01-21 19:08 UTC, titovmx commented on src/content/learn/synchronizing-with-effects.md
> +Имейте в виду, что `setInterval` возвращает идентификатор интервала, который вы можете передать в [`clearInterval`](https://developer.mozilla.org/en-US/docs/Web/API/clearInterval), чтобы остановить и
```suggestion
Имейте в виду, что `setInterval` возвращает идентификатор интервала, который вы можете передать в [`clearInterval`](https://developer.mozilla.org/ru/docs/Web/API/clearInterval), чтобы остановить интервал.
```

2025-02-07 07:32 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +Имейте в виду, что `setInterval` возвращает идентификатор интервала, который вы можете передать в [`clearInterval`](https://developer.mozilla.org/en-US/docs/Web/API/clearInterval), чтобы остановить и
Нет перевода...

2025-02-07 07:33 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +Некоторые API могут ограничивать возможность вызывать их дважды подряд. Например, метод [`showModal`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal) встроенного элемент
К сожалению, https://developer.mozilla.org/ru/docs/Web/API/HTMLDialogElement/showModal ссылка не работает, потому что статья доступна только в оригинале.

2025-02-07 07:33 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +- **Обработчики событий** (подробнее [Добавление интерактивности](/learn/adding-interactivity)) — это вложенные функции внутри ваших компонентов, которые *выполняют действия*, а не просто их вычисляю
Исправила

2025-02-07 07:34 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +Здесь и далее в тексте «Эффект», написанный с заглавной буквы, относится к приведенному выше определению, специфичному для React, то есть к побочному эффекту, вызванному рендерингом. Чтобы отличать е
Исправила: «_Чтобы отличать его от концепта, применимого в программировании в целом, мы будем называть последний «побочные эффекты»._ »

2025-02-07 07:35 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +2. **Укажите зависимости Эффекта.** Большинство Эффектов должны перезапускаться только *когда это необходимо*, а не при каждом рендере. Например, анимация должна срабатывать только когда компонент по
Спасибо, узнала новое. Исправила.

2025-02-07 07:35 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +Ваш компонент `VideoPlayer` рендерит встроенный в браузер тег [`<video>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video):
Исправила

2025-02-07 07:36 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +Эффекты обычно должны синхронизировать ваши компоненты с *внешней* системой. Если это не внешняя система и вы только хотите обновить одно состояние на основе другого состояния, [возможно, вам не нуже
Поправила

2025-02-07 07:37 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +Массив зависимостей может содержать несколько элементов. React пропустит повторный запуск Эффекта только в том случае, если *все* указанные вами зависимости имеют точно такие же значения, как и во вр
Исправила

2025-02-07 07:37 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +Чтобы устранить ошибку, не достаточно просто сделать так, чтобы Эффект срабатывал один раз. Эффект должен корректно работать после повторного монтирования, что означает, что соединение должно быть оч
Упс) Поправила.

2025-02-07 07:37 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +Обратите внимание, что в этом случае очистка не требуется. В режиме разработки React вызовет Эффект дважды, но это не проблема, потому что вызов `setZoomLevel` дважды с одним и тем же значением ничег
Исправила везде.

2025-02-07 07:38 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +В процессе разработки Эффект будет вызывать `addEventListener()`, затем сразу `removeEventListener()`, а затем снова `addEventListener()` с тем же обработчиком. Таким образом, в любой момент времени
Исправила

2025-02-07 07:38 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +Вы не можете "отменить" сетевой запрос, который уже был выполнен, но ваша функция очистки должна гарантировать, что запрос, который _больше не актуален_, не продолжит влиять на ваше приложение. Если
Исправила везде

2025-02-07 07:38 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +**В продакшн-режиме будет только один запрос.** Если второй запрос в процессе разработки вас беспокоит, лучшим подходом будет использование решения, которое устраняет дублирование запросов и кэширует
Исправила

2025-02-07 07:39 UTC, Tata-Sysueva commented on src/content/learn/synchronizing-with-effects.md
> +Вот почему вы видите биографию Боба, даже когда выбрана Тейлор. Ошибки такого рода называются [гонки состояний](https://en.wikipedia.org/wiki/Race_condition), потому что две асинхронные операции "сор
Исправила

2025-05-12 16:20 UTC, dimatitov commented
@titovmx @Тата-Сысуева
Привет! Ссылка https://developer.mozilla.org/ru/docs/Web/API/clearInterval ведёт на страницу “Page not found” — русской версии этой статьи пока нет.
Предлагаю оставить англоязычную ссылку https://developer.mozilla.org/en-US/docs/Web/API/clearInterval, как в оригинале.

2025-05-13 00:41 UTC, Tata-Sysueva commented
> @titovmx @Tata-Sysueva Привет! Ссылка https://developer.mozilla.org/ru/docs/Web/API/clearInterval ведёт на страницу “Page not found” — русской версии этой статьи пока нет. Предлагаю оставить англоязычную ссылку https://developer.mozilla.org/en-US/docs/Web/API/clearInterval, как в оригинале.

Да, точно, в одном месте пропустила. Исправила

2025-05-17 15:17 UTC, titovmx approved these changes

2025-05-17 15:17 UTC, merged